#!/usr/bin/sh
# 用于在Gnome环境下将包括KDE程序集在内的无关程序移入下述文件夹中，以节省程序界面的空间。
# Gnome本身将在3.34版本优化此项目，支持在程序界面拖动图标来创建文件夹，在host系统更新到3.34版本前仍使用此方法有效。

# Utilities:
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Utilities/ apps "['org.kde.falkon.desktop','git-gui.desktop','org.gnome.Screenshot.desktop','com.teamviewer.TeamViewer.desktop','org.gnome.DiskUtility.desktop','org.gnome.Calculator.desktop','masterpdfeditor5.desktop','org.gnome.bijiben.desktop','calc.desktop','impress.desktop','writer.desktop','gnome-system-monitor.desktop','gnome-tweak-tool.desktop','org.gnome.Software.desktop','vinagre.desktop']"


# Sundry:
gsettings set org.gnome.desktop.app-folders.folder:/org/gnome/desktop/app-folders/folders/Sundry/ apps "['system-config-printer.desktop','org.kde.showfoto.desktop','org.kde.skanlite.desktop','simple-scan.desktop','swell-foop.desktop','PTBatcherGUI.desktop','calibrate_lens_gui.desktop','flashplayer.desktop','flash-player-properties.desktop','org.kde.akregator.desktop','org.kde.ark.desktop','org.kde.kcharselect.desktop','org.kde.kcolorchooser.desktop','org.kde.klipper.desktop','qt4config.desktop','qterminal.desktop','qterminal_drop.desktop','org.kde.kmousetool.desktop','org.kde.ktnef.desktop','org.kde.knotes.desktop','org.kde.kompare.desktop','org.kde.konsole.desktop','konsolesu.desktop','org.kde.kontact.desktop','org.kde.konversation.desktop','org.kde.korganizer.desktop','org.kde.kleopatra.desktop','org.kde.kmag.desktop','org.kde.kmail2.desktop','org.kde.kaddressbook.desktop','org.kde.kate.desktop','org.kde.kcalc.desktop','org.kde.gwenview.desktop','org.kde.sieveeditor.desktop','org.kde.dolphin.desktop','org.gnome.Weather.Application.desktop','org.gnome.Totem.desktop','xterm.desktop','org.kde.okular.desktop','hugin.desktop','org.kde.discover.desktop','org.kde.digikam.desktop','wps-office-pdf.desktop','vlc.desktop','kdesystemsettings.desktop','kde_wacom_tabletfinder.desktop','claws-mail.desktop','org.kde.ksysguard.desktop','org.kde.kwalletmanager5.desktop','mutt.desktop','pcmanfm-qt.desktop','org.kde.pimsettingexporter.desktop','obconf.desktop','vncviewer.desktop','org.kde.marble.desktop','org.kde.dolphinsu.desktop','fcitx-configtool.desktop','fcitx.desktop','org.kde.kdeconnect.kcm.desktop','org.kde.kdeconnect.nonplasma.desktop','ibus-setup.desktop','iagno.desktop','eog.desktop','brasero.desktop','org.gnome.Characters.desktop','org.gnome.Cheese.desktop','org.gnome.clocks.desktop','org.gnome.Contacts.desktop','org.gnome.Dictionary.desktop','org.gnome.Documents.desktop','gnome-chess.desktop','ca.desrt.dconf-editor.desktop','gnome-mahjongg.desktop','gnome-mines.desktop','gnome-sudoku.desktop','org.gnome.Logs.desktop','org.gnome.Maps.desktop','org.gnome.PackageUpdater.desktop','org.gnome.Photos.desktop','org.gnome.Polari.desktop','org.gnome.PowerStats.desktop','quadrapassel.desktop','seahorse.desktop','lightsoff.desktop','pidgin.desktop','gnome-printers-panel.desktop','pavucontrol-qt.desktop','gpk-prefs.desktop','lximage-qt.desktop','jconsole.desktop','startcenter.desktop','math.desktop','draw.desktop','base.desktop','org.kde.spectacle.desktop','yelp.desktop','org.kde.Help.desktop','org.gnome.Music.desktop','evince.desktop','evolution.desktop','org.gnome.baobab.desktop','org.gnome.FileRoller.desktop']"
